### ISSUE TITLE
More key bindings

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#112]
Here are some key bindings I have in my `init.moon` file that might be useful to add to Howl itself:

- `ctrl_shift_k` for `editor-delete-line`: This one is really, REALLY useful. I'm addicted. :)
- `ctrl_shift_x` for `buffer-close`: `ctrl_shift_w` might actually be a better fit for this one. Basically, when using processes, I also use this one a lot.
- `ctrl_shift_h` for `buffer-replace-regex`: Handy for replacing variable names, since you can stuff like `\b` to restrict the replace to just words.

Thoughts?

**Comment by shalabhc** [comment]
I like this. In general, I feel default bindings for these commands make sense.

> ctrl_shift_k for editor-delete-line

I don't have a shortcut for this yet but it sounds useful.

> ctrl_shift_x for buffer-close

I have a heavily used binding for `buffer-close` too - I use `alt_w`. I do think it makes sense to add a binding for this command to Howl.

> ctrl_shift_h for buffer-replace-regex

You can already invoke `buffer-replace-regex` by first pressing `ctrl_h` for `buffer-replace` and then pressing `ctrl_r` to switch to the regex command. Do you think a direct binding to `buffer-replace-regex` still makes sense?

**Comment by kirbyfan64** [comment]
@shalabhc

> You can already invoke `buffer-replace-regex` by first pressing `ctrl_h` for buffer-replace and then pressing `ctrl_r` to switch to the regex command.

Huh...I didn't realize that. I guess the direct binding doesn't really make that much sense then.

Another one I just thought of is `ctrl_g`, which could pop up a box and then scroll to the

**Comment by kirbyfan64** [comment]
@shalabhc

> You can already invoke `buffer-replace-regex` by first pressing `ctrl_h` for buffer-replace and then pressing `ctrl_r` to switch to the regex command.

Huh...I didn't realize that. I guess the direct binding doesn't really make that much sense then.

Another one I just thought of is `ctrl_g`, which could pop up a box and then scroll to the

**Comment by kirbyfan64** [comment]
(stupid GitHub for mobile)

...the given line.

**Comment by shalabhc** [comment]
BTW, if you press `ctrl_g` and type the line number it will most likely jump to the line you want. I use this often - it's `buffer-grep` of course, not line number specific command, but it searches through line numbers too. A jump-to-line command may be useful too - @nilnor?

**Comment by nilnor** [comment]
I've commented on #122 for the goto line command. I can't believe we don't already have a standard binding for closing a buffer, I have my own and so haven't thought about it :P 

As @shalabhc says there's already a way of switching from the ordinary replace to regex replace. The problem there is that it's invisible. Personally I knew about it, but have still been using `buffer-replace-regex` manually since I also quickly forgot about it. We need to provide visual feedback during an interaction of what the available bindings, if any, are. This is the same for all interactions providing shortcuts of course.

So, `ctrl_shift_k` for delete line sounds fine. Exactly what we should have for the buffer closing I'm not sure - anyone got any feedback on the most commonly used shortcut  for this?

**Comment by shalabhc** [comment]
I have another request: `ctrl_n` for `buffer-new`. I use this often and it's a pretty standard shortcut.

I personally feel `ctrl_w` is a better fit for `buffer-close` than `view-close`, which is it current bound to. Consider if all open files were tabs, `ctrl_w` would just close the current tab (i.e. buffer). Chrome uses `ctrl_w` for  'close tab', Gimp uses `ctrl_w` for closing the current image. Gedit and Atom use `ctrl_w` to close the current tab. So to me this feels like 'close the current document' rather than 'close the current view'. But changing existing shortcuts needs a higher bar of support - does anyone use `ctrl_w` to close views?

Regarding visual feedback for shortcuts within an interaction - I agree. We could add an 'info bar' - basically a text box showing a list of shortcuts available. But how about showing something in the command list (i.e. `alt_x`, `tab`)? The shortcut might be more easily discovered there, no?

**Comment by kirbyfan64** [comment]
If `ctrl_w` is changed to close buffers, then `ctrl_shift_w` should close views.

**Comment by shalabhc** [comment]
I'll try and summarize so we can get some of these in:

* `editor-delete-line`: @kirbyfan64 suggests `ctrl_shift_k`
* `buffer-close`: @kirbyfan64 suggests `ctrl_shift_x` or `ctrl_shift_w`. @shalabhc suggests `ctrl_w` but it steals that shortcut from `view-close`
* `buffer-new`: @shalabhc suggests `ctrl_n`

Already implemented:
* `buffer-replace-regex`:  `ctrl_g` -> `ctrl_g`
* `goto-line`: `alt_g`

Here are a couple of new suggestions from me:

* `cursor-start`: `ctrl_home`
* `cursor-eof`: `ctrl_end`

**Comment by nilnor** [comment]
Added bindings for 'editor-delete-line' and 'new-buffer'. I am in favour of adopting `ctrl_w` for closing buffers and then using `ctrl_shift_w` for closing views, but it would obviously also be backwards incompatible, so it would need to be mentioned clearly in the release notes.

**Comment by nilnor** [comment]
So, should we go with the `ctrl_w` change or not? I'm eager to close this now (@shalabh, for the other suggestions just open a PR).

**Comment by shalabhc** [comment]
`ctrl_w` change sounds good to me.

I'll open a new PR for `cursor-start` and `cursor-eof` shortcuts.
