### ISSUE TITLE
Improve buffer switching usability with mulitiple views

### ISSUE THREAD

**Issue by shalabhc** [howl-editor/howl#143]
When two views are open and `buffer-swtich` is invoked, the two visible buffers occupy the top two positions in the buffer list. This has two usability issues:

1. If the topmost buffer was not the one in the current view, the view is immediately switched (due to preview) to the topmost buffer so that both views now show the same buffer. Invoking `buffer-switch` should not switch the visible buffer until arrows are used. Also, it's very unlikely that the user wants to switch to the buffer already visible in the other view.

2. If the topmost buffer is one from the current view, the next buffer is the one from the other view and it's unlikely the user wants to switch to that - so the user would just end up skipping over the next buffer (or buffers) that are already displayed.

I'm not sure what the right solution here is. Couple of options:

1. Always show the buffer list so that the current buffer is the last in the set of visible buffers, and is selected by default. This means the user would have to press `up` to select another visible buffer and `down` to select a non-visible buffer.

2. Push all visible buffers (except current) to the end of the list - these are still select-able by `up`, but will not clutter the visible list and the topmost buffer will always be the current one.

**Comment by nilnor** [comment]
I think it makes sense to have the buffer that's currently active being the first in the list, particularly if previews are enabled. I believe that having the buffer being replaced right away just as the prompt opens would be jarring. Also, it makes more sense as the list is ordered by last shown anyway. In short, I'm not sure I see this as a big issue. However, the currently active buffer should always be at the top of the list though, so that's not optimal.

**Comment by shalabhc** [comment]
OK. I will try and update `last_shown` for the current buffer when any command is invoked. Hopefully that will fix the ordering for this command (and all others based on last shown).

**Comment by shalabhc** [comment]
Fixed via a different (and I think better approach) via 157fb11aeecfe5d4c489499fe9245c10653ae25d.
