### ISSUE TITLE
Howl can clear out files!

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#147]
This is quite possibly the most ANNOYING bug EVER!!!!!

Howl can occasionally freeze. Which is fine. However, if you were trying to save when Howl froze, and then you force-close it, _the file will be completely empty upon reopening_. I just lost several days of work because of this.

It's hard to reproduce this, but it's still really bad.

**Comment by nilnor** [comment]
It sounds like there's some special stuff going on here. For one, I very seldom happen upon freezes, and when I do it's because of some kind of code that I'm writing that misbehaves. Does your freezes typically occur when you save? Furthermore, there's nothing special going one when it comes to saving, it's a plain open and write and close. The whole procedure is blocking though. It's sounds like you're saving to a misbehaving file system, are you using a remote mount?

Anyway, it makes sense to improve this generally. I'm thinking we could save to a temporary file in the same directory and then do an atomic rename instead. Also, it would be nice for the remote scenario to switch to a non-blocking save and implement a time-out.

**Comment by kirbyfan64** [comment]
@nilnor Well:

1. Howl will just occasionally *freeze* for me. It only happens once in a while, and it always lasts a second or so. I've never been able to accurately reproduce it; it seems totally random. The problem is when I hit save and then hit close, but in froze in the middle. Also, no remote mount.

2. Yeah, I've seen the temporary file strategy used elsewhere.

**Comment by shalabhc** [comment]
Howl had frozen on me, but it's rare and it hasn't happened recently. I also use a lot of remote folders so I assumed that has something to do with it.

Regarding renaming, one thing to consider is any other apps that have the same file open will not see the changes if a rename is used. Other apps will continue to use the old inode unless they are specifically designed to track renames. I also just verified that both emacs and vi use the same inode.

If the freeze happens after open but before a write call, and then the process exits (of the file is closed) I believe the file will be truncated. It's a shame there's no OS functionality to atomically replace contents. Hmm, maybe we can implement a C function that just does an `open` operation followed by a `write` operation (and maybe also a `flush` or `close`). Perhaps it is much likely to freeze or crash because control does not re-enter the Lua runtime between these calls?

**Comment by shalabhc** [comment]
Other issues with rename might be that hard links may break and symbolic links may get replaced with a file.

**Comment by nilnor** [comment]
So, good points in favour of not doing any renaming upon save. As it is, I have a hard time seeing how this would be a bug per se in Howl. As @shalabhc says, a truncated file indicates a freeze between the open and the write, and nothing really happens between these two from Howl's side. It could of course be something like the GC kicking in right between, but it still seems more likely to be something going awry on the system side for the write. (As an aside I've personally experienced general system slowdowns/freezes which resolves themselves after trimming the SSD disk).

Doing the whole thing with renaming is also just a case of adding additional safe guarding for the save functionality. If we don't want to do the rename thing, another piece of functionality that could be added would be to add support for creating backup files prior to saving, and deleting them afterwards. Ideally coupled with some checks when opening the files, asking to restore the files from the backup if it exists. Thoughts?

**Comment by kirbyfan64** [comment]
I like the backup idea, as long as the backup files don't end with `~` like Gedit's (too scary to delete: `rm *~` looks to similar to `rm ~`!).

I'm positive that this isn't an FS problem. Again, Howl has frozen for a second or so before when idling or pressing `alt_x`, two things that have nothing to do with disk drives! It also happens on both my hard drives.

I really like @shalabhc's idea of putting it in C code. There is very little that could occur in the background that can cause issues there!!

**Comment by shalabhc** [comment]
Rewriting in C will sidestep any Lua runtime related issues - such as the GC kicking in, which may have an occasional bug - but it won't prevent any shenanigans from other threads, and I'm not sure how many other threads GTK runs. While we could manually disable the GC for the duration of the `save` operation, I don't know of other runtime things that may happen. I think rewriting in C is a speculative fix for the reported issue, but at least it *seems* like it should improve reliability of the `save`. 

I do like the idea of making a backup of the original before overwriting. This obviates the need for rewriting in C as there is always a fallback to the previous version. This is related to another idea around automatic revisions - i.e. automatically storing previous versions of edited files. If every save makes a new backup copy instead of overwriting the old one, we end up with multiple revisions. These files would go in `.howl` instead of the file's parent directory I think? If we do automatic backups, I'd prefer this over a single backup in the file's directory.

@kirbyfan64 - if you see freezes that last a longish time, are you able to do `ps` and some gdb investigation to see where it is frozen? Perhaps we should consider adding something like faulthandler (https://pypi.python.org/pypi/faulthandler/) to Howl, where sending a signal to the process dumps the current Lua call stacks? Even if it's a system problem, this feature may help investigation.

**Comment by kirbyfan64** [comment]
Only problem is that the freezes are 1-2s long, so I never have enough time to run `ps` or anything. :(

**Comment by kirbyfan64** [comment]
Somehow I managed to get this again. Thank goodness this time is was a "disposable" document (though it still sucks).
