### ISSUE TITLE
Backspace before whitespace doesn't move cursor as expected

### ISSUE THREAD

**Issue by shalabhc** [howl-editor/howl#150]
1. Open a new buffer
2. Type 3 spaces followed by 'a'
3. Position cursor after first space (i.e. column 2)
4. Press `backspace`

The space is deleted, however the cursor is now at column 3 instead of column 1.

**Comment by nilnor** [comment]
This is also by design. I'm not saying it necessarily has to be this way, but it's working as intended. When the configuration variable `backspace_unindents` is true and we're in leading indentation we unindent and move the cursor to the first non-blank column. Not something new in master either, this behaviour is the same as it always has been.

**Comment by shalabhc** [comment]
I see.

The unindent action is expected, but moving the cursor right when I'm asking it to go left seems a bit odd. In this particular case I was trying to merge the current line into the previous so pressing `backspace` twice seemed the obvious way (I was on the column 2). However the cursor jump foiled my plan. Given other readily available commands - `ctrl_right` to jump to the start of the word  and `shift_tab` to unindent - is there a specific reason behind the jump right on `backspace`, or is it just incidental?

**Comment by shalabhc** [comment]
FWIW, I also find it a bit jarring that `shift_tab` makes the cursor jump to the first non blank character. In my mental model, deletion of text should only move the cursor if the text before the cursor was deleted. So successive `shift_tab`s on a line would look like this (cursor shown as `|`):

```
    |    abc
    |  abc
    |abc
  |abc
|abc
```

**Comment by nilnor** [comment]
I'm open for a PR changing this behaviour. It's currently the way it is since that's how it worked with Scintilla, and I kept the behaviour as much as possible when replacing it with aullar. Both these cases are now handled in `Editor`, so the code there should be changed along with the accompanying specs.

**Comment by shalabhc** [comment]
OK. I have a couple of other things in the pipeline so I'll leave the bug open and get to a PR for this later.

**Comment by shalabhc** [comment]
Fixed by #184
