### ISSUE TITLE
Insertion into read-only buffer works

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#155]
Basically, I noticed that, if you run an external command with Howl, you can insert text into the `ProcessBuffer`, even though it's read-only. Interestingly, you CANNOT replace text...because it's read-only!

This seems to be because [`howl.Editor.insert`](https://github.com/howl-editor/howl/blob/master/lib/howl/ui/editor.moon#L379) calls [`aullar.View.insert`](https://github.com/howl-editor/howl/blob/master/lib/aullar/view.moon#L310), which always calls [`aullar.Buffer.insert`](https://github.com/howl-editor/howl/blob/master/lib/aullar/buffer.moon#L157) instead of [`howl.Buffer.insert`](https://github.com/howl-editor/howl/blob/master/lib/howl/buffer.moon#L152). This skips the [check to make sure that the buffer is writable](https://github.com/howl-editor/howl/blob/master/lib/howl/buffer.moon#L296).

**Comment by nilnor** [comment]
After looking at it the problem is not that the `Editor.insert` does not check the status (which is also a problem), but that the key presses and corresponding inserts are handled by the aullar view. So, we have to move down some read-only support into aullar, or add some kind of veto-notification thing.
