### ISSUE TITLE
Bizarre issue with replacing text in REALLY large file

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#160]
Well, this is...interesting...

Download [this huge, 700-line file C source file](http://pastebin.com/9UZXMk16). Now, open the file in Howl, hit Ctrl-H to replace text, and enter `m->groups`, then enter a slash to move on to the replacement text. Notice that Howl selects the wrong region of text to replace:

![howl_sel0](https://cloud.githubusercontent.com/assets/1690697/13020706/86605d7a-d19c-11e5-99ab-4ef97c10825e.png)

Now, *anything* you type will proceed to completely wreck the remainder of the file:

![howl_sel1](https://cloud.githubusercontent.com/assets/1690697/13020708/87bdd800-d19c-11e5-975b-25bb2f77cde8.png)

**Comment by shalabhc** [comment]
I cannot reproduce this in master. Here are my screenshots - works as expected. Anything special with your config or file?

![replace-1](https://cloud.githubusercontent.com/assets/7066873/13024658/33ac5870-d1ad-11e5-9ea7-bf5b4eeff431.png)
![replace-1](https://cloud.githubusercontent.com/assets/7066873/13024659/3aca1aca-d1ad-11e5-95c9-1e20826bf5ba.png)
![replace-3](https://cloud.githubusercontent.com/assets/7066873/13024663/401c8616-d1ad-11e5-9baf-b37c70ebcc94.png)

**Comment by kirbyfan64** [comment]
Well, this is *weird*.

If I try it on the file anywhere else, it works correctly.

BUT...

If I save the file as `~/rejit2/tst.c`, then the bug appears!

**Comment by kirbyfan64** [comment]
Here's how to reproduce it:

1. Clone [ReJit](https://github.com/kirbyfan64/rejit) somewhere.
2. Open `tst.c` in that directory.

Any other way will cause the bug not to appear. This is easily the weirdest bug I've ever come across...

**Comment by shalabhc** [comment]
OK, I can reproduce this now by the instructions above. I haven't found the root issue but I suspect it is either in aullar/buffer.moon or in replacement.moon.

The following patch fixes it for me, @kirbyfan64 can you verify it fixes it for you too?:
```
--- a/lib/howl/interactions/replacement.moon
+++ b/lib/howl/interactions/replacement.moon
@@ -285,6 +285,7 @@ class Replacement
     highlight.remove_all 'replace_strikeout', @preview_buffer
 
   _highlight_match: (name, pos, len) =>
+    @preview_buffer.text
     highlight.apply name, @preview_buffer, pos, len
 
   _toggle_current: =>
```

I discovered this because I wasn't able to reproduce the issue once I added the log that accessed `preview_buffer.text`.

I'm also having trouble reducing the test case itself. It seems some combination of the below is needed:

* large-ish file
* multiple matches
* multi-byte character between matches

I suspect calling `preview_buffer\chunk(...) = ...` to replace some chunk (line 241 in replacement.py) has something to do with it.

Still looking, ideas welcome...

**Comment by shalabhc** [comment]
I can reproduce the problem by using the buffer API directly, so I think the bug is in `aullar.buffer`.

1. Download tst.c: `wget https://github.com/kirbyfan64/rejit/raw/master/tst.c`

2. Run howl, open a new buffer, paste below code. Select all and `howl-moon-eval`:

  ```moonscript
  howl.bindings.push
    f2: ->
      buffer = howl.app.editor.buffer
      first = 26985
      last = 27376

      text = buffer\chunk(first, last).text
      buffer\chunk(first, last).text = text
  ```

3. Open `tst.c`, go to line 759

4. Press `f2` to run the test code above.

The buffer text changes, even though the text should not because the replacement is identical.

@nilnor - sorry, couldn't reduce the test case to something simpler.

**Comment by nilnor** [comment]
@kirbyfan64 Thanks for the report, and thanks @shalabhc for drilling down and making it easy to reproduce! Should be fixed now, but please verify if you have a moment.

**Comment by kirbyfan64** [comment]
@nilnor Yup, that fixed the issue!
