### ISSUE TITLE
Useless directory showing

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#179]
![dir_lst](https://cloud.githubusercontent.com/assets/1690697/13558030/960065b0-e3bf-11e5-91c5-b26822e7fc31.png)

Not sure why `[howl]` is appearing there, considering there isn't even any ambiguity and `howl` isn't actually the direct parent of the shown paths (it's `lib`).

The command I used to open the files was (run in the Howl source directory):

```
$ howl spec/buffer_spec.moon spec/editing/auto_pair_spec.moon lib/aullar/buffer.moon lib/howl/buffer.moon
```

**Comment by shalabhc** [comment]
This is as-intended due to #153. The `[howl]` part is the containing project, not parent. I feel any codified scheme for naming ends up  being confusing in certain cases but I'm open to suggestions. The current logic is to try the following adornments sequentially while duplicate titles that exist:

1. show project
2. show project and parent directory
3. show project and two levels of parent directories

**Comment by kirbyfan64** [comment]
@shalabhc What if that instead becomes:

1. show project
2. show *just* parent directory
3. show project and parent directory
4. show project and two levels of parent directories

**Comment by shalabhc** [comment]
@kirbyfan64, sounds good to me. I'll get to this at some point but feel free to submit a PR if you want. The code is pretty straightforward: https://github.com/howl-editor/howl/blob/master/lib/howl/interactions/buffer_selection.moon#L61
