### ISSUE TITLE
Clipboard weirdness

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#235]
This is somewhat odd and hard to reproduce accurately, but, sometimes, if I open up Howl, then copy something from, say, Chrome, and try to paste it into Howl, it won't paste. Again, it's super hard to reproduce correctly, but I'm trying to see if I can at least get a modest test case.

**Comment by nilnor** [comment]
I recognize this fwiw, but I don't have an easy solution to it unfortunately. The problem occurs when you have more than one instance open as far as I can tell. I therefore speculate that it's something to do  with dbus/X11/Gtk (as we register the application on dbus via GApplication). So I don't think it's necessarily a bug in Howl per se, but I could of course be wrong - perhaps there's something we're doing wrong in the app init, etc., which has this effect. Anyway, perhaps there's a work around to be found, but it happens only now and then as you've said so that makes is harder to experiment. That it happens with multiple instances open is as far as I've narrowed it down until now, but if a reproducible test case could be found that would be great.
