### ISSUE TITLE
inspector 'function 0x........' failed: error in error handling

### ISSUE THREAD

**Issue by zatherz** [howl-editor/howl#256]
Open a Moonscript file with this text:
```
test\test() \test "?"

```

This doesn't happen with this code:
```
test\test()\test "?"

```
Note the space before the last `\test` in the first example and the lack of it in the second example

**Comment by nilnor** [comment]
Thanks for the report! I've fixed it as best as I could from the Howl side, which unfortunately still turned out to be sub par. The originating issue is with the moonscript linter, which just bubbles up an internal error when called. That error does not contain any position information, so while the error now be viewed we have no choice but to place it one one of the lines (the first one was chosen). A better solution is dependent on fixing the moonscript linter itself, which is developed outside of Howl.

**Comment by zatherz** [comment]
[Reported on Moonscript's issue tracker, this is actually a problem with the moonscript compiler](https://github.com/leafo/moonscript/issues/283)
