### ISSUE TITLE
The naming scheme for commands is awkward for discoverability

### ISSUE THREAD

**Issue by ozra** [howl-editor/howl#321]
I lifted this out from #314 since it's a contained issue enough.

- Currently the command names follow a synthetic sentence style, kind of pseudo-object-oriented language.
- In the germanic languages "thought-flow", verbs come first. Wherever you're from - if you're coding - you're in contact with English enough for that to stick I think.
- When it's often attempted to follow English sentence flow even in tests/specs (BDD), it's crazy to not adhere to it in command names.
- When I want to add a new view to the right: what pops into my head to start typing in command line is... Yep! You guessed it! `add-new-view-to-the-right` ;-) 
- Discoverability is the most important factor to make a tool naturally gradually more usable to a human user with minimum effort.

(Also see issue #319 for thoughts on having additional short-names for core commands - power usage.)

**Comment by nilnor** [comment]
Yes, the command names are currently grouped, which I think has benefits as well. As for discoverability, I think the matching helps out a lot anyway; if you don't know what the command is, aren't you just as likely to type "view" in this case since that's what you're working with?

I believe you raise valid points, but also think that the current theme has its benefits, and I'm hesitant to change all command names at this point. It would require massive support for the idea from others at any rate, but unless that happens I'll close this.

**Comment by shalabhc** [comment]
In spite of not matching the English language grammar, I like the command names as they are because:

- This groups the commands for the same object together. I think this is better for discoverability because typically I want to discover all operations for this object (e.g. 'show me operations I can do for a view'), more often than I want to find all objects I can do an operation on (e.g. 'show me everything I can *add*'). 
- There tends to be less ambiguity in object names (e.g. `buffer`, `view` etc have no typical aliases) compared to  verb names (add? append? new? open?) - so and object name based search seems like a more natural and effective way to go.
- It matches the underlying syntax more often for the actual command (e.g. `buffer-replace` -> `buffer\replace`
- Finally, the full text matching includes the description so something like 'add view' does indeed find the right command.

**Comment by ozra** [comment]
I definitely understand reluctance to turn it all upside down after being established for such time. I'm just thinking the long picture here: Howl will inevitably be the vim/emacs/sublime/your-previous-favourite-here of tomorrow X-D - so taking some plunges before 1.0.0 could be beneficial - before there are too many bundles to grep...

On one hand, the grouping associated with underlying implementation structure is probably neither self-evident nor interesting to many users (designers, stylers, doc-writers, and also a large group of... hmm, how do I put it, "floor workers programmers" that.. well, does their jobs, and that's that).

On the other, @shalabhc makes a good practical point: helpful hints for _API discoverabilty_ for those who _do want to open the hood_ of the muscle car.

Perhaps _changing_ the names was a rather crude suggestion of mine: rather, what was touched upon in #314: _configurable choice of matching/ranking algo_ - is the ring to rule them all.

Let's just keep this open for a little while @nilnor et al? Just to gather some perspectives at least?

**Comment by ozra** [comment]
After a nights sleep: I'll close this, there's not much more to discuss about it. I believe configurable core-funcs like matcher/ranker etc. is likely the way.
