### ISSUE TITLE
Can't open file navigator

### ISSUE THREAD

**Issue by sheosi** [howl-editor/howl#329]
So, it seems that any operation that tries to open file navigator (Ctrl+O to open or Ctrl+S to save) results in this error on the statusbar:
`../lib/aullar/buffer.moon:289: Out of range recursive change (1578, 1) <> (1, 1577)`

Now some information:
Linux distribution: Solus OS
Way of installation: Self-made package
GTK version: 22.9

**Comment by nilnor** [comment]
Since this is the first report of this, presumably it has something to do with the contents of the directory you're trying to open or something else specific to your environment. Have you tried running Howl from different directories and and see if the problem persists when running the `open` command?

**Comment by sheosi** [comment]
So, I just tried that, i tried both of them at diffrents places of my home directory and even at root, in case anyone tries to consider, before asking this I've cleaned my .howl folder.

This is pretty weird, it was working wonderfully until I updated my system and this started happening. I tried to rebuild it, to no effect.

**Comment by nilnor** [comment]
Hmm, so it used to work then..You're on the latest solus (Solus 2017.01.01 or so?). I can try a virtualbox and see if the problem appears there as well.

**Comment by sheosi** [comment]
So, I've fiddling with Howl a bit more, and it's weird, using master didn't fix it, though it worked launching it as root through sudo.

**Comment by nilnor** [comment]
Missed your edits there, thanks for the update. FWIW I tried Solus but couldn't reproduce, and after that I was thinking that perhaps your locale had changed during the upgrade which would lead to file names being reported differently by the system and cause a unicode mismatch. This turned out not to be not that differently. I can reproduce the rendering bug and will have a look at that, hopefully solving that will also solve the more serious bug.

**Comment by nilnor** [comment]
When you have a moment, it would be great if you could check the latest master. The rendering bug is fixed, so would be nice to know if that also fixes the first issue.

**Comment by sheosi** [comment]
Works perfect :+1:

**Comment by nilnor** [comment]
Excellent, thanks!
