### ISSUE TITLE
Provide a way of re-enabling the titlebar

### ISSUE THREAD

**Issue by zesterer** [howl-editor/howl#419]
Personally, I don't use a tiling window manager. However, I remember the keybindings I need to manipulate a window; but many users do not. The option to re-enable the title bar would be useful for new or inexperienced users. This setting would preferably not be hidden deep in the settings (although it's useful to provide a hook for the init script to use). Perhaps a tiny icon in the corner of the window?

**Comment by kirbyfan64** [comment]
I'm really confused by this. Tiling WMs pretty much always let you enable the title bar explicitly, and if anything, Gtk+ has been pushing to *remove* title bars...

**Comment by zesterer** [comment]
The move to CSD means that apps get control over their own title bar, rather than removing them entirely. In its current incarnation, it's impossible to drag Howl around the screen as you would a normal window without first holding 'Alt', despite there being adequate space for a draggable widget. I believe Gtk allows you to assign arbitrary widgets to act as draggable regions?

**Comment by kirbyfan64** [comment]
But...I'm using GNOME, and I see the titlebars...

**Comment by zesterer** [comment]
On master? I don't. I see this:
![image](https://user-images.githubusercontent.com/3268430/37247900-7ce32416-24bb-11e8-8bcc-80934dad9868.png)
And without using keyboard shortcuts, it's awfully difficult for users to figure out how they can reverse maximising the window such that they can see the title bar again.

**Comment by kirbyfan64** [comment]
![screenshot from 2018-03-10 18-12-40](https://user-images.githubusercontent.com/1690697/37248121-a28dbbfe-248e-11e8-8778-d70b4c2b5add.png)

I have the titlebar. What DE are you using? Are you sure it's that it isn't explicitly asking Gtk+ to disable CSD?

**Comment by zesterer** [comment]
I'm using Budgie. The title bars work on all other apps (other than the ones I've specifically requested should not have title bars, of course).

**Comment by nilnor** [comment]
The only thing explicitly done with regards to titlebars in Howl is to request them to be hidden when maximized. You don't say whether you're referring to maximized windows, nor does your screenshot help in this regard, but I'm guessing this is not what you're seeing? You can experiment with disabling this if you like:

https://github.com/howl-editor/howl/blob/master/lib/howl/ui/window.moon#L53

Apart from that I tried the budgie desktop locally (on plain Ubuntu) and could not reproduce. What do you mean when you say you're using Budgie, the stand-alone OS version?

**Comment by zesterer** [comment]
Budgie Desktop on Arch Linux.

The behaviour, as you described, is intended. When maximised (or when attached to the side of a screen) Howl has no title bar. While not a negative thing in itself, my first reaction was that it must be a problem with my window manager and spent 10 minutes trying to figure out why it was happening. At this point, the only way to undo the maximisation was to use `Super+Down`. This isn't a problem on its own, but the fact that it is the **only** way to reverse this is problematic for users that don't remember their WM's keyboard shortcuts. I'd suggest that a small icon/button in the corner of the window would be appropriate to fix this usability issue.

**Comment by ryanplusplus** [comment]
@zesterer I'm not sure about Budgie, but in Gnome Shell you can click on the menu bar and drag down to un-maximize a window (as if the menu bar were the maximized window's title bar). This may be helpful for you in the future since Howl is not the only application I've seen with this behavior.

**Comment by zesterer** [comment]
@ryanplusplus  Budgie does not have that behaviour. Given that that behaviour isn't standardised, I think it's a good idea that Howl handles this usability case rather than hoping the window manager does. Now that CSD are purely the domain of applications, it makes sense to handle title bar usability issues in applications too.

**Comment by nilnor** [comment]
Note that while CSD might be purely the domain of applications in some sense, Howl does not actually do anything with regards to the title bar except setting the aforementioned flag; Gtk provides a default implementation of the title bar. In order to actually customize the appearance of the title bar right now we would have to actually do our own implementation first, and then it wouldn't actually be hidden at all anyway unless we made it so (since the flag pertains to the default implementation). At any rate, it seems like the problem here is that the flag isn't desirable to begin with in this case. The problem is that it makes Howl fit better into other environments, such as Gnome 3, so just disabling it again isn't necessarily optimal either. We could as I see it either

1) Make it configurable in Howl using an option
2) Try to find some heuristic that allows us to conditionally enable it (e.g only for Gnome 3?)

Thoughts? Also, any good ideas about 2) would be welcome

**Comment by zesterer** [comment]
Is it not possible to make the top of the editor a draggable window region?

**Comment by nilnor** [comment]
It might be possible, but it does not strike me as an ideal solution either. By the "top of the editor", you must be referring to either header bar for a editor view or to the padding space above the editor(s) that happens to be there in the current themes. If there are more than one view at a given time it would make more sense to use the drag of a editor view to allow for rearranging the views within the editors rather than moving the entire window. And as mentioned we're not guaranteed to have any space above the editor views at all since that's a theme detail.

That being said, I might possibly experiment some with it. I'm more leaning towards making it a configurational option now however, off by default.

**Comment by bugabinga** [comment]
Personally, I was glad to see the title bar off by default in my case.
I work on a 13" screen most of the time.

I would like to challenge the idea about the "hypothetical, new human using howl, that is not familiar with its DE" a little.
The desire to make a program friendly to newcomers is understandable.
But why not spend attention on more fun parts of howl until there is actual evidence of newcomers struggling with howls title bar?
If the argument is to say, that newcomers likely won't report initial hurdles, then that is a interesting problem to discuss.
But it won't make our guesses about the actual hurdles more accurate.

Of course, if someone here feels the need to change the title bar thing, I will not complain as long as I can turn them off ;).
