### ISSUE TITLE
Jump-to command?

### ISSUE THREAD

**Issue by refi64** [howl-editor/howl#47]
This is kind of a big feature request, but it's a cool one.

I was recently toying with the [acme](http://acme.cat-v.org/) text editor. I'm not rather fond of the move-the-mouse-like-crazy design concept, but there is one feature that's pretty neat.

Right now in Howl, you can run commands with `exec`. Acme lets you do that, too, albeit in a different way. Both open the command's output in a new buffer/view.

However, acme has one key feature here. Say the C compiler outputs this text:

```
tst.c:1: error: you did something stupid
```

If you right-click on the part that says `tst.c:1`, acme will open that file and jump to the given line number. This can be really handy with long C/C++ programs. I was thinking that maybe Howl could have this in the form of a key sequence. For instance, I'd click somewhere inside the `tst.c:1` part and press something like `ctrl_shift_j`.

Thoughts?

**Comment by nilnor** [comment]
This is a given, we should definitely have excellent support for this (as well as other navigation features). At the moment it's rather crude, and not well advertized, but it's actually already there - try pressing `enter` on the line to go to the referenced line. I just checked in a small improvement of this as a result of testing it, so fetch the latest master again for the best results.

**Comment by kirbyfan64** [comment]
@nilnor Looks neat! I didn't realize it was there.

**Comment by shalabhc** [comment]
This is a great suggestion. May I propose that we use a simple action such as just a click (or ctrl-click) to jump to the line? That would be easier to discover and use.

**Comment by kirbyfan64** [comment]
I would prefer ctrl+click over a plain click, since I'm pretty sure a plain click jumping me source files might get a tad confusing and/or scary. :)

**Comment by nilnor** [comment]
Yes, just click would be confusing since if you like using the mouse you would probably use the simple click for selecting text. At any rate it would be confusing unless the area was clearly marked up as a link.

This is currently only available for process buffers. I think it might be a good idea to generalize this into a command, e.g. `go-to-file` that could be made smarter and also handle file references in includes and requires, etc. And at the process buffer could do a better job of advertizing the available functionality, say by highlighting the reference when the cursor is at that line and logging something like 'Press [enter] to go to foobar/myfile'.

**Comment by shalabhc** [comment]
I believe this is implemented (not in terms of click but pressing enter) - should we close this @refi64 ?

**Comment by refi64** [comment]
Will test tomorrow, was hoping to today but got swamped.

**Comment by refi64** [comment]
God, meant to comment that on #533, yeah this can be closed.
