### ISSUE TITLE
Weird selection behavior with aullar

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#72]
I just tried the `aullar` branch. It looks great, but there are two weird selection issues:

1. If I double-click a line, it selects the whole thing. If I click it again, it deselects it. That's normal. *But*, if I do the three clicks past the end of the line, it never deselects.
2. When a selection is active, clicking removes it like usual. However, there's this weird "dead zone"-type area at the very end of the selection. If you click there nothing happens.

I also noticed that there's no horizontal scrollbar OR word wrapping (even though I have it the line wrapping setting on `word`), so it's hard to see the rest of the line, and the cursor is the normal pointer instead of the I-style thing that it should be while over a text entry. The space between characters also seems to be much more, so that fewer characters fit on a line (around 78-ish vs. 83).

Other than that, everything works! :D

**Comment by nilnor** [comment]
There are multiple issues crammed into one here, but I think all of them of are addressed or not issues per se:

1) As it stands, one click moves the cursor, two clicks selects the current word, and three clicks select the entire line. So when you triple click at the end of a line it will select the entire line, as it should. There might be other issues with this logic, but the three clicks at the end of the line does what it should.

2) Has been addressed via 58a4892 

The horizontal scrollbar or word wrap has been addressed by turning on horizontal scrollbar by default, and word wrapping is a thing of its own that will have to be addressed. There's nothing special done for spacing between characters, so that seems like it it would depend on the font.

So I'm closing this, if there's anything you'd like to revisit then open a separate issues.
