### ISSUE TITLE
Popups don't always close in time

### ISSUE THREAD

**Issue by kirbyfan64** [howl-editor/howl#94]
Basically:

1. Open a new file.
2. Type something.
3. Search for the something you typed.
4. Hit `Ctrl-F` again to make the message about the search hitting the bottom appear.
5. Quickly hit the close button.

When the unsaved buffer popup appears, the text about the search hitting the bottom is still there. At one point in my experimenting, I managed to get the `Yes/No` selection to be covered by the find box. Weird.

**Comment by shalabhc** [comment]
I'm not sure what you mean by "the Yes/No selection to be covered by the find box" - it you can take a screenshot the next time you see it, that would be great.

The first behavior you describe is expected since interactions stack on each other - so if you select `No` it will drop back into the search interaction. However, in this specific case stacking might be confusing and it makes more sense to hide other interactions when the quit confirmation is triggered.

**Comment by kirbyfan64** [comment]
@shalabhc Well, basically, it showed the text about closing unsaved buffers, but, instead of the yes/no selection, it was the find box entry.

**Comment by shalabhc** [comment]
OK. I think the proper fix here would be to hide all interaction widgets when one of the quitting commands is triggered. I'll have to think about the details of the implementation.
